name: 'Deploy action'
description: 'This action perform a rolling update on a given list of EC2 instances inside a target group'
inputs:
  aws-secret-access-key:
    description: AWS secret
    required: true
    default: ""
  aws-secret-key-id:
    description: AWS secret id
    required: true
    default: ""
  arn-target-group:
    description: EC2's target group
    required: true
    default: ""
  npm-token:
    description: NPM admin token for building the project
    required: true
    default: ""
  command:
    description: |
      command the will be executed in the ssh session. 
      Must be a onliner (join multiples command with &&)
    required: true
    default: ""
  sha:
    description: Sha of the commit to be deployed
    required: true
    default: ""
  base64-encoded-ssh-key:
    description: base64 encoded ssh key used to connect to instance
    required: true
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base64-encoded-ssh-key }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.aws-secret-key-id }}
    - ${{ inputs.arn-target-group }}
    - ${{ inputs.npm-token }}
    - ${{ inputs.command }}
    - ${{ inputs.sha }}
